runtime: python39
entrypoint: gunicorn -b :$PORT index:app

env_variables:
  DB_CONNECTION_NAME: appointment-system-deployment:asia-southeast1:dainyisheree
  DB_USER: dainyisheree
  DB_PASSWORD: 123456
  DB_NAME: OnlineAppointmentSystem
  DB_HOST: 34.124.252.236
  INSTANCE_NAME: dainyisheree
  PROJECT_ID: appointment-system-deployment
  REGION: asia-southeast1
  GAE_ENV: standard